GTV: Parent entities
Parent entities
Functions
GtsEdge * gtv_vertex_has_parent_volume (GtsVertex *p, GtvVolume *v)
GtvFacet * gtv_edge_has_parent_volume (GtsEdge *e, GtvVolume *v)
GtvCell * gtv_facet_has_parent_volume (GtvFacet *f, GtvVolume *v)
gboolean gtv_cell_has_parent_volume (GtvCell *c, GtvVolume *v)
guint gtv_edge_facet_number (GtsEdge *e, GtvVolume *v)
guint gtv_facet_cell_number (GtvFacet *f, GtvVolume *v)
Detailed Description
Function Documentation
gboolean gtv_cell_has_parent_volume (GtvCell * c, GtvVolume * v)
Check if a GtvCell belongs to a given GtvVolume.
Parameters
c a GtvCell;
v a GtvVolume.
Returns
TRUE if c belongs to v, FALSE otherwise.
Referenced by gtv_cell_neighbours(), gtv_edge_cells(), gtv_facet_cell_number(), gtv_facet_has_parent_volume(), gtv_facet_is_boundary(), and gtv_vertex_cells().
guint gtv_edge_facet_number (GtsEdge * e, GtvVolume * v)
Count the number of facets using an edge.
Parameters
e a ::GtsEdge;
v a GtvVolume.
Returns
the number of facets of v which contain e.
References gtv_facet_has_parent_volume().
GtvFacet* gtv_edge_has_parent_volume (GtsEdge * e, GtvVolume * v)
Check if a ::GtsEdge has a given parent volume.
Parameters
e a ::GtsEdge;
v a GtvVolume.
Returns
a GtvFacet of v containing e, NULL otherwise.
References gtv_facet_has_parent_volume().
Referenced by gtv_vertex_has_parent_volume().
guint gtv_facet_cell_number (GtvFacet * f, GtvVolume * v)
Count the number of cells using a facet.
Parameters
f a GtvFacet;
v a GtvVolume.
Returns
the number of cells of v which contain f.
References gtv_cell_has_parent_volume().
GtvCell* gtv_facet_has_parent_volume (GtvFacet * f, GtvVolume * v)
Check if a GtvFacet has a given parent volume.
Parameters
f a GtvFacet;
v a GtvVolume.
Returns
a GtvCell of v containing f, NULL otherwise.
References gtv_cell_has_parent_volume().
Referenced by gtv_edge_facet_number(), and gtv_edge_has_parent_volume().
GtsEdge* gtv_vertex_has_parent_volume (GtsVertex * p, GtvVolume * v)
Check if a ::GtsVertex has a given parent volume.
Parameters
p a ::GtsVertex;
v a GtvVolume.
Returns
a ::GtsEdge of v containing p, NULL otherwise.
References gtv_edge_has_parent_volume().