GTV: Point location in a volume
Point location in a volume
Functions
GtvCell * gtv_point_locate_slow (GtsPoint *p, GtvVolume *volume, GtvCell *guess)
GtvCell * gtv_point_locate (GtsPoint *p, GtvVolume *volume, GtvCell *guess)
Detailed Description
Function Documentation
GtvCell* gtv_point_locate (GtsPoint * p, GtvVolume * volume, GtvCell * guess)
Locate a point in a triangulation using a remembering stochastic walk (Olivier Devillers, Sylvain Pion and Monique Teillaud, 2002, `Walking in a triangulation', International Journal of Foundations in Computer Science, 13:181–199). Note that at present this will not work for volumes with holes in their interior.
Parameters
p a GtsPoint to locate;
volume a GtvVolume;
guess a GtvCell which is an initial guess for a cell containing p or NULL.
Returns
a GtvCell containing p or NULL if p is not in volume.
References gtv_point_in_tetrahedron(), and gtv_tetrahedron_opposite().
Referenced by gtv_delaunay_add_vertex().
GtvCell* gtv_point_locate_slow (GtsPoint * p, GtvVolume * volume, GtvCell * guess)
Find a GtvCell in a given volume which encloses a ::GtsPoint by sequentially testing the cells. This is not a very good way of locating a point but it does work and can be used in testing other point location methods.
Parameters
p a ::GtsPoint;
volume a GtvVolume to search for the location of p;
guess ignored, included for compatibility with other location functions.
Returns
a GtvCell containing p or NULL if p is not in v.
References gtv_point_in_tetrahedron(), and gtv_volume_foreach_cell().