GTV: Cells
Cells
Data Structures
struct GtvCell
struct GtvCellClass
Functions
GtvCellClass * gtv_cell_class (void)
GtvCell * gtv_cell_new (GtvCellClass *klass, GtvFacet *f1, GtvFacet *f2, GtvFacet *f3, GtvFacet *f4)
GSList * gtv_cell_neighbours (GtvCell *c, GtvVolume *v)
GtvCell * gtv_cell_new_from_vertices (GtvCellClass *klass, GtvFacetClass *facet_class, GtsEdgeClass *edge_class, GtsVertex *v1, GtsVertex *v2, GtsVertex *v3, GtsVertex *v4)
GSList * gtv_edge_cells (GtsEdge *e, GtvVolume *v)
GSList * gtv_vertex_cells (GtsVertex *p, GtvVolume *v)
Detailed Description
Function Documentation
GtvCellClass* gtv_cell_class (void)
The basic class for cells (volume elements) in GTV.
Returns
the GtvCellClass
References gtv_tetrahedron_class().
Referenced by gtv_cell_new_from_vertices().
GSList* gtv_cell_neighbours (GtvCell * c, GtvVolume * v)
Find the neighbours of a GtvCell.
Parameters
c a GtvCell;
v a GtvVolume, or NULL.
Returns
a ::GSList of the cells of v, or any cells if v is NULL, which share a facet with c.
References gtv_cell_has_parent_volume().
GtvCell* gtv_cell_new (GtvCellClass * klass, GtvFacet * f1, GtvFacet * f2, GtvFacet * f3, GtvFacet * f4)
Make a new GtvCell from four facets which must define a proper tetrahedron.
Parameters
klass a GtvCellClass;
f1 a GtvFacet;
f2 another GtvFacet;
f3 a further GtvFacet;
f4 one more GtvFacet;
Returns
the new GtvCell.
References gtv_tetrahedron_set().
Referenced by gtv_cell_new_from_vertices(), and gtv_volume_read().
GtvCell* gtv_cell_new_from_vertices (GtvCellClass * klass, GtvFacetClass * facet_class, GtsEdgeClass * edge_class, GtsVertex * v1, GtsVertex * v2, GtsVertex * v3, GtsVertex * v4)
Generate a new GtvCell from four ::GtsVertex's, making use of any existing GtvFacet's which connect them.
Parameters
klass a GtvCellClass
facet_class a GtvFacetClass
edge_class a ::GtsEdgeClass
v1 a ::GtsVertex
v2 a ::GtsVertex
v3 a ::GtsVertex
v4 a ::GtsVertex
Returns
the new GtvCell
References gtv_cell_class(), gtv_cell_new(), and gtv_tetrahedron_from_facets().
GSList* gtv_edge_cells (GtsEdge * e, GtvVolume * v)
Find the GtvCell's which use a given ::GtsEdge.
Parameters
e a ::GtsEdge
v a GtvVolume
Returns
a ::GSList of the GtvCell's of v which contain e, NULL if e is not used by any cells.
References gtv_cell_has_parent_volume().
GSList* gtv_vertex_cells (GtsVertex * p, GtvVolume * v)
Find the GtvCell's which use a given ::GtsVertex
Parameters
p a ::GtsVertex;
v a GtvVolume or NULL.
Returns
a ::GSList of the GtvCell's of v which contain e, NULL if e is not used by any cells.
References gtv_cell_has_parent_volume().