GTV: Volume
Volume
Data Structures
struct GtvVolume
struct GtvVolumeClass
struct GtvVolumeStats
struct GtvVolumeQualityStats
Functions
GtvVolumeClass * gtv_volume_class (void)
GtvVolume * gtv_volume_new (GtvVolumeClass *klass, GtvCellClass *cell_class, GtvFacetClass *facet_class, GtsEdgeClass *edge_class, GtsVertexClass *vertex_class)
gint gtv_volume_add_cell (GtvVolume *v, GtvCell *c)
gint gtv_volume_remove_cell (GtvVolume *v, GtvCell *c)
gint gtv_volume_write (GtvVolume *v, FILE *f)
guint gtv_volume_read (GtvVolume *v, GtsFile *f)
gint gtv_volume_foreach_cell (GtvVolume *v, GtsFunc func, gpointer data)
gint gtv_volume_foreach_facet (GtvVolume *v, GtsFunc func, gpointer data)
gint gtv_volume_foreach_edge (GtvVolume *v, GtsFunc func, gpointer data)
gint gtv_volume_foreach_vertex (GtvVolume *v, GtsFunc func, gpointer data)
gint gtv_volume_stats (GtvVolume *v, GtvVolumeStats *s)
gint gtv_volume_quality_stats (GtvVolume *v, GtvVolumeQualityStats *s)
gint gtv_volume_print_stats (GtvVolume *v, FILE *f)
gint gtv_volume_boundary (GtvVolume *v, GtsSurface *s)
gdouble gtv_volume_volume (GtvVolume *v)
GtsVertex * gtv_volume_nearest_vertex (GtvVolume *v, GtsPoint *p)
gint gtv_volume_write_tetgen (GtvVolume *v, gchar *stub)
guint gtv_volume_read_gmsh (FILE *f, GtvVolume *v)
gint gtv_volume_write_gmsh1 (GtvVolume *v, FILE *f)
gint gtv_volume_write_gmsh (GtvVolume *v, FILE *f)
GtsBBox * gtv_bbox_volume (GtsBBoxClass *klass, GtvVolume *v)
Detailed Description
Function Documentation
GtsBBox* gtv_bbox_volume (GtsBBoxClass * klass, GtvVolume * v)
Generate a bounding box containing a GtvVolume.
Parameters
klass a ::GtsBBoxClass;
v a GtvVolume.
Returns
a ::GtsBBox which contains v.
References gtv_volume_foreach_vertex().
gint gtv_volume_add_cell (GtvVolume * v, GtvCell * c)
Add a GtvCell to a GtvVolume.
Parameters
v GtvVolume
c GtvCell
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, and GTV_WRONG_TYPE.
Referenced by gtv_delaunay_add_vertex_to_cell(), and gtv_volume_read().
gint gtv_volume_boundary (GtvVolume * v, GtsSurface * s)
Add the boundary facets of a GtvVolume to a GtsSurface.
Parameters
v GtvVolume
s GtsSurface to take boundary facets
Returns
GTV_SUCCESS on success
References GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_volume_foreach_facet(), and GTV_WRONG_TYPE.
GtvVolumeClass* gtv_volume_class (void)
Generate the class definition for the GtvVolume type.
Returns
GtvVolumeClass.
gint gtv_volume_foreach_cell (GtvVolume * v, GtsFunc func, gpointer data)
Execute a function for each cell of a GtvVolume.
Parameters
v GtvVolume;
func a GtsFunc to be evaluated for each cell;
data data to be passed to function.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, and GTV_WRONG_TYPE.
Referenced by gtv_delaunay_check(), gtv_point_locate_slow(), gtv_volume_quality_stats(), gtv_volume_stats(), gtv_volume_volume(), gtv_volume_write(), gtv_volume_write_gmsh(), gtv_volume_write_gmsh1(), and gtv_volume_write_tetgen().
gint gtv_volume_foreach_edge (GtvVolume * v, GtsFunc func, gpointer data)
Execute a function for each edge of a GtvVolume.
Parameters
v GtvVolume;
func a GtsFunc to be evaluated for each edge;
data data to be passed to function.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, and GTV_WRONG_TYPE.
Referenced by gtv_volume_quality_stats(), gtv_volume_stats(), and gtv_volume_write().
gint gtv_volume_foreach_facet (GtvVolume * v, GtsFunc func, gpointer data)
Execute a function for each facet of a GtvVolume.
Parameters
v GtvVolume;
func a GtsFunc to be evaluated for each facet;
data data to be passed to function.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, and GTV_WRONG_TYPE.
Referenced by gtv_volume_boundary(), gtv_volume_quality_stats(), gtv_volume_stats(), and gtv_volume_write().
gint gtv_volume_foreach_vertex (GtvVolume * v, GtsFunc func, gpointer data)
Execute a function for each vertex of a GtvVolume.
Parameters
v GtvVolume;
func a GtsFunc to be evaluated for each vertex;
data data to be passed to function.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, and GTV_WRONG_TYPE.
Referenced by gtv_bbox_volume(), gtv_volume_nearest_vertex(), gtv_volume_stats(), gtv_volume_write(), gtv_volume_write_gmsh(), gtv_volume_write_gmsh1(), and gtv_volume_write_tetgen().
GtsVertex* gtv_volume_nearest_vertex (GtvVolume * v, GtsPoint * p)
Find the vertex of a tetrahedralization which is nearest a ::GtsPoint.
Parameters
v a GtvVolume;
p a ::GtsPoint.
Returns
the vertex of v which is closest to p, NULL in case of an error.
References gtv_volume_foreach_vertex().
GtvVolume* gtv_volume_new (GtvVolumeClass * klass, GtvCellClass * cell_class, GtvFacetClass * facet_class, GtsEdgeClass * edge_class, GtsVertexClass * vertex_class)
Generate a new GtvVolume
Parameters
klass GtvVolumeClass for new volume
cell_class GtvCellClass
facet_class GtvFacetClass
edge_class GtsEdgeClass
vertex_class GtsVertexClass
Returns
the new GtvVolume
gint gtv_volume_print_stats (GtvVolume * v, FILE * f)
Print out basic statistics about a GtvVolume
Parameters
v GtvVolume
f file pointer
Returns
GTV_SUCCESS on success
References GtvVolumeQualityStats::cell_quality, GtvVolumeQualityStats::cell_volume, GtvVolumeStats::cells_per_facet, GtvVolumeQualityStats::edge_length, GtvVolumeStats::edges_per_vertex, GtvVolumeQualityStats::facet_area, GtvVolumeQualityStats::facet_quality, GtvVolumeStats::facets_per_edge, GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_volume_quality_stats(), gtv_volume_stats(), GTV_WRONG_TYPE, GtvVolumeStats::n_boundary_facets, GtvVolumeStats::n_cells, GtvVolumeStats::n_duplicate_cells, GtvVolumeStats::n_duplicate_edges, GtvVolumeStats::n_duplicate_facets, and GtvVolumeStats::n_incompatible_cells.
gint gtv_volume_quality_stats (GtvVolume * v, GtvVolumeQualityStats * s)
Fill a GtvVolumeQualityStats with the geometrical quality information for a GtvVolume.
Parameters
v a GtvVolume;
s a GtvVolumeQualityStats to be filled with data.
Returns
GTV_SUCCESS on success.
References GtvVolumeQualityStats::cell_quality, GtvVolumeQualityStats::cell_volume, GtvVolumeQualityStats::edge_angle, GtvVolumeQualityStats::edge_length, GtvVolumeQualityStats::facet_area, GtvVolumeQualityStats::facet_quality, GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_volume_foreach_cell(), gtv_volume_foreach_edge(), gtv_volume_foreach_facet(), GTV_WRONG_TYPE, and GtvVolumeQualityStats::parent.
Referenced by gtv_volume_print_stats().
guint gtv_volume_read (GtvVolume * v, GtsFile * f)
Read a volume from file, adding its cells to the GtvVolume v.
Parameters
v GtvVolume to add cells to;
f GtsFile to read from.
Returns
GTV_SUCCESS on success, otherwise the line number where the error occurred.
References gtv_cell_new(), gtv_facet_new(), GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_volume_add_cell(), and GTV_WRONG_TYPE.
guint gtv_volume_read_gmsh (FILE * f, GtvVolume * v)
Read a GMSH mesh file (.msh extension) from a file, adding its elements to a GtvVolume.
Parameters
f input file;
v a GtvVolume.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, GTV_UNKNOWN_FORMAT, and GTV_WRONG_TYPE.
gint gtv_volume_remove_cell (GtvVolume * v, GtvCell * c)
Remove a GtvCell from a GtvVolume. If gtv_allow_floating_cells is FALSE, the cell will be destroyed if it is not used by any other GtvVolume.
Parameters
v GtvVolume;
c GtvCell to remove.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, and GTV_WRONG_TYPE.
Referenced by gtv_delaunay_add_vertex_to_cell().
gint gtv_volume_stats (GtvVolume * v, GtvVolumeStats * s)
Find basic statistics for a volume
Parameters
v GtvVolume
s GtvVolumeStats to fill with data
Returns
GTV_SUCCESS on success
References GtvVolumeStats::cells_per_facet, GtvVolumeStats::edges_per_vertex, GtvVolumeStats::facets_per_edge, GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_volume_foreach_cell(), gtv_volume_foreach_edge(), gtv_volume_foreach_facet(), gtv_volume_foreach_vertex(), GTV_WRONG_TYPE, GtvVolumeStats::n_boundary_facets, GtvVolumeStats::n_cells, GtvVolumeStats::n_duplicate_cells, GtvVolumeStats::n_duplicate_edges, GtvVolumeStats::n_duplicate_facets, GtvVolumeStats::n_facets, GtvVolumeStats::n_incompatible_cells, GtvVolumeStats::n_incompatible_facets, and GtvVolumeStats::parent.
Referenced by gtv_volume_print_stats(), gtv_volume_write(), gtv_volume_write_gmsh(), gtv_volume_write_gmsh1(), and gtv_volume_write_tetgen().
gdouble gtv_volume_volume (GtvVolume * v)
Volume of a GtvVolume, found as the sum of the cell volumes.
Parameters
v GtvVolume
Returns
volume of v
References gtv_volume_foreach_cell(), and GTV_WRONG_TYPE.
gint gtv_volume_write (GtvVolume * v, FILE * f)
Write a GtvVolume to file. The file's first line is the number of vertices, edges, facets and cells respectively, followed by the class of each in the volume. There then follow the vertex coordinates, one vertex per line, and then the edges, facets and cells.
Parameters
v GtvVolume to write;
f file pointer.
Returns
GTV_SUCCESS on success.
References GtvVolumeStats::cells_per_facet, GtvVolumeStats::edges_per_vertex, GtvVolumeStats::facets_per_edge, GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_volume_foreach_cell(), gtv_volume_foreach_edge(), gtv_volume_foreach_facet(), gtv_volume_foreach_vertex(), gtv_volume_stats(), GTV_WRONG_TYPE, and GtvVolumeStats::n_cells.
gint gtv_volume_write_gmsh (GtvVolume * v, FILE * f)
Write a GtvVolume to file as a GMSH .msh (format 2.0, favoured) file.
Parameters
v a GtvVolume;
f file to which v is to be written.
Returns
GTV_SUCCESS on success.
References GtvVolumeStats::edges_per_vertex, GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_volume_foreach_cell(), gtv_volume_foreach_vertex(), gtv_volume_stats(), GTV_WRONG_TYPE, and GtvVolumeStats::n_cells.
gint gtv_volume_write_gmsh1 (GtvVolume * v, FILE * f)
Write a GtvVolume to file as a GMSH .msh (format 1.0, deprecated) file.
Parameters
v a GtvVolume;
f file to which v is to be written.
Returns
GTV_SUCCESS on success.
References GtvVolumeStats::edges_per_vertex, GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_volume_foreach_cell(), gtv_volume_foreach_vertex(), gtv_volume_stats(), GTV_WRONG_TYPE, and GtvVolumeStats::n_cells.
gint gtv_volume_write_tetgen (GtvVolume * v, gchar * stub)
Write a GtvVolume to .node and .ele files which can be read by tetgen, to allow checking and comparisons.
Parameters
v a GtvVolume;
stub the stub file name. Files will be written to stub.node and stub.ele.
Returns
GTV_SUCCESS on success.
References GTV_FAILURE, GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_volume_foreach_cell(), gtv_volume_foreach_vertex(), gtv_volume_stats(), GTV_WRONG_TYPE, and GtvVolumeStats::n_cells.