GTV: Delaunay tetrahedralization
Delaunay tetrahedralization
Functions
GtvCell * gtv_delaunay_check (GtvVolume *v)
gint gtv_delaunay_add_vertex_to_cell (GtvVolume *v, GtsVertex *p, GtvCell *c)
gint gtv_delaunay_add_vertex (GtvVolume *v, GtsVertex *p, GtvCell *c)
gboolean gtv_facet_is_regular (GtvFacet *f)
Detailed Description
Function Documentation
gint gtv_delaunay_add_vertex (GtvVolume * v, GtsVertex * p, GtvCell * c)
Add a ::GtsVertex to a GtvVolume, preserving the Delaunay property.
Parameters
v a GtvVolume;
p a ::GtsVertex to be added to v;
c a GtvCell which is an initial guess for the location of p, or NULL.
Returns
GTV_SUCCESS on insertion of p in v, or an appropriate error code.
References gtv_delaunay_add_vertex_to_cell(), GTV_NULL_ARGUMENT, gtv_point_locate(), GTV_VERTEX_NOT_IN_VOLUME, and GTV_WRONG_TYPE.
gint gtv_delaunay_add_vertex_to_cell (GtvVolume * v, GtsVertex * p, GtvCell * c)
Add a ::GtsVertex to a GtvCell of a GtvVolume, restoring the Delaunay property of the volume, using the method of Edelsbrunner, H. and Shah, N. R., Algorithmica 15:223–241, 1996 and Lawson, C., Computer Aided Geometric Design, 3:231–246, 1986, as described in Ledoux, H., `Computing the 3D Voronoi diagram robustly: An easy explanation', 4th International Symposium on Voronoi Diagrams in Science and Engineering, 2007.
Parameters
v a GtvVolume;
p a ::GtsVertex to add to p;
c a GtvCell to add p to.
Returns
GTV_SUCCESS on success, non-zero if p is already part of c or coincides with a vertex of c.
References GTV_COINCIDENT_VERTEX, gtv_edge_is_boundary(), gtv_facet_is_boundary(), GTV_IN, GTV_NULL_ARGUMENT, GTV_ON_EDGE, GTV_ON_FACET, GTV_ON_VERTEX, gtv_point_in_tetrahedron(), gtv_point_in_tetrahedron_sphere(), GTV_SUCCESS, gtv_tetrahedron_facet_opposite(), gtv_tetrahedron_opposite(), gtv_tetrahedron_vertex_opposite(), gtv_tetrahedron_vertices(), GTV_VERTEX_NOT_IN_CELL, GTV_VERTEX_ON_HULL, GTV_VERTEX_PRESENT, gtv_volume_add_cell(), gtv_volume_remove_cell(), and GTV_WRONG_TYPE.
Referenced by gtv_delaunay_add_vertex().
GtvCell* gtv_delaunay_check (GtvVolume * v)
Check whether a GtvVolume satisfies the Delaunay property.
Parameters
v volume to check
Returns
a non-Delaunay GtvCell of v if v is non-Delaunay, NULL otherwise.
References gtv_volume_foreach_cell().
gboolean gtv_facet_is_regular (GtvFacet * f)
Check if a GtvFacet is regular. A facet is regular if neither of the tetrahedra using it has the apex of the opposite tetrahedron inside its circumsphere. Boundary facets and isolated facets are also considered regular.
Parameters
f a GtvFacet.
Returns
TRUE if f is regular, FALSE otherwise.
References gtv_point_in_tetrahedron_sphere(), and gtv_tetrahedron_vertex_opposite().
Referenced by gtv_tetrahedron_is_encroached().