GTV: Tetrahedra
Tetrahedra
Data Structures
struct GtvTetrahedron
struct GtvTetrahedronClass
Functions
GtvTetrahedronClass * gtv_tetrahedron_class (void)
gint gtv_tetrahedron_set (GtvTetrahedron *tetrahedron, GtvFacet *f1, GtvFacet *f2, GtvFacet *f3, GtvFacet *f4)
GtvTetrahedron * gtv_tetrahedron_new (GtvTetrahedronClass *klass, GtvFacet *f1, GtvFacet *f2, GtvFacet *f3, GtvFacet *f4)
gint gtv_tetrahedron_vertices (GtvTetrahedron *t, GtsVertex **v1, GtsVertex **v2, GtsVertex **v3, GtsVertex **v4)
gdouble gtv_tetrahedron_volume (GtvTetrahedron *t)
gboolean gtv_tetrahedron_has_facet (GtvTetrahedron *t, GtvFacet *f)
GtvTetrahedron * gtv_tetrahedron_from_facets (GtvFacet *f1, GtvFacet *f2, GtvFacet *f3, GtvFacet *f4)
GtvTetrahedron * gtv_tetrahedron_is_duplicate (GtvTetrahedron *t)
gdouble gtv_point_in_tetrahedron_sphere (GtsPoint *p, GtvTetrahedron *t)
GtvIntersect gtv_point_in_tetrahedron (GtsPoint *p, GtvTetrahedron *t, gpointer *s)
GtvTetrahedron * gtv_tetrahedron_large (GtvTetrahedronClass *klass, GtvFacetClass *facet_class, GtsEdgeClass *edge_class, GtsVertexClass *vertex_class, gdouble len)
GtvTetrahedron * gtv_tetrahedron_equilateral (GtvTetrahedronClass *klass, GtvFacetClass *facet_class, GtsEdgeClass *edge_class, GtsVertexClass *vertex_class, gdouble len)
GtvFacet * gtv_tetrahedra_common_facet (GtvTetrahedron *t1, GtvTetrahedron *t2)
GtvTetrahedron * gtv_tetrahedron_opposite (GtvTetrahedron *t, GtvFacet *f)
gdouble gtv_tetrahedron_orientation (GtvTetrahedron *t)
gint gtv_tetrahedron_facets (GtvTetrahedron *t, GtvFacet **f1, GtvFacet **f2, GtvFacet **f3, GtvFacet **f4)
gint gtv_tetrahedron_invert (GtvTetrahedron *t)
GtsVertex * gtv_tetrahedron_vertex_opposite (GtvTetrahedron *t, GtvFacet *f)
GtvFacet * gtv_tetrahedron_facet_opposite (GtvTetrahedron *t, GtsVertex *v)
gboolean gtv_tetrahedron_is_okay (GtvTetrahedron *t)
GtvTetrahedron * gtv_tetrahedron_new_from_vertices (GtvTetrahedronClass *klass, GtvFacetClass *facet_class, GtsEdgeClass *edge_class, GtsVertex *v1, GtsVertex *v2, GtsVertex *v3, GtsVertex *v4)
GtvTetrahedron * gtv_tetrahedron_from_vertices (GtsVertex *v1, GtsVertex *v2, GtsVertex *v3, GtsVertex *v4)
gboolean gtv_tetrahedron_has_edge (GtvTetrahedron *t, GtsEdge *e)
gboolean gtv_tetrahedron_has_vertex (GtvTetrahedron *t, GtsVertex *v)
GtvTetrahedron * gtv_tetrahedra_wedge_neighbour (GtvTetrahedron *t1, GtvTetrahedron *t2)
GtvFacet * gtv_point_in_tetrahedron_facet (GtvTetrahedron *t, GtsPoint *p)
gint gtv_tetrahedron_vertices_off_edge (GtvTetrahedron *t, GtsEdge *e, GtsVertex **a, GtsVertex **b)
gint gtv_tetrahedron_opposite_vertices (GtvTetrahedron *t, GtsVertex *v, GtsVertex **v1, GtsVertex **v2, GtsVertex **v3)
gint gtv_tetrahedron_orient (GtvTetrahedron *t)
GtsVertex * gtv_tetrahedron_is_encroached (GtvTetrahedron *t)
gdouble gtv_tetrahedron_inradius (GtvTetrahedron *t)
gdouble gtv_tetrahedron_circumradius (GtvTetrahedron *t)
gdouble gtv_tetrahedron_quality_radius_ratio (GtvTetrahedron *t)
GtsBBox * gtv_bbox_tetrahedra (GtsBBoxClass *klass, GSList *tetrahedra)
gint gtv_tetrahedron_centroid (GtvTetrahedron *t, GtsPoint *c)
gdouble gtv_tetrahedron_radius_ratio (GtvTetrahedron *t)
Detailed Description
A convenience macro for the quality measure of a tetrahedron. This actually calls gtv_tetrahedron_radius_ratio, although the behaviour may change in future.
Function Documentation
GtsBBox* gtv_bbox_tetrahedra (GtsBBoxClass * klass, GSList * tetrahedra)
Generate a bounding box for a list of tetrahedra
Parameters
klass a ::GtsBBoxClass;
tetrahedra a ::GSlist of ::GtvTetrahedrons.
Returns
a ::GtsBBox which contains the tetrahedra in tetrahedra.
References gtv_tetrahedron_vertices().
GtvIntersect gtv_point_in_tetrahedron (GtsPoint * p, GtvTetrahedron * t, gpointer * s)
Check if a ::GtsPoint lies in a GtvTetrahedron, using the method given by Gary Herron.
Parameters
p a ::GtsPoint;
t a GtvTetrahedron;
s if NULL, ignored; if not NULL, set to the vertex, edge or facet of t which p intersects, or NULL if p lies strictly inside or strictly outside t.
Returns
GTV_OUT if p is strictly outside t and GTV_IN if it lies strictly inside t. If p lies on the surface of t, returns GTV_IN if s is NULL, otherwise GTV_ON_FACET, GTV_ON_EDGE or GTV_ON_VERTEX if it lies on a facet, edge or vertex of t respectively.
References GTV_IN, GTV_ON, GTV_ON_EDGE, GTV_ON_FACET, GTV_ON_VERTEX, and gtv_tetrahedron_vertices().
Referenced by gtv_delaunay_add_vertex_to_cell(), gtv_point_locate(), and gtv_point_locate_slow().
GtvFacet* gtv_point_in_tetrahedron_facet (GtvTetrahedron * t, GtsPoint * p)
Find the facet of a GtvTetrahedron on which lies a ::GtsPoint.
Parameters
t a GtvTetrahedron;
p a ::GtsPoint.
Returns
the facet of t which contains p, i.e. p lies in the plane of the facet and inside or on its boundary.
References gtv_tetrahedron_vertices().
gdouble gtv_point_in_tetrahedron_sphere (GtsPoint * p, GtvTetrahedron * t)
Check whether a point lies inside or outside the circumsphere of a tetrahedron.
Parameters
p a ::GtsPoint;
t a GtvTetrahedron.
Returns
positive value if p lies inside t, zero if lies on t and a negative value if it lies outside t.
References gtv_point_in_sphere(), and gtv_tetrahedron_vertices().
Referenced by gtv_delaunay_add_vertex_to_cell(), and gtv_facet_is_regular().
GtvFacet* gtv_tetrahedra_common_facet (GtvTetrahedron * t1, GtvTetrahedron * t2)
Find the facet shared by two tetrahedra.
Parameters
t1 a GtvTetrahedron;
t2 another GtvTetrahedron.
Returns
the GtvFacet between t1 and t2, if they neighbour each other, NULL otherwise.
GtvTetrahedron* gtv_tetrahedra_wedge_neighbour (GtvTetrahedron * t1, GtvTetrahedron * t2)
Find a GtvTetrahedron which lies in the `wedge' between two other tetrahedra.
Parameters
t1 a GtvTetrahedron;
t2 another GtvTetrahedron;
Returns
a GtvTetrahedron which shares one facet with t1 and another facet with t2, if it exists, NULL otherwise.
References gtv_tetrahedron_opposite().
gint gtv_tetrahedron_centroid (GtvTetrahedron * t, GtsPoint * c)
Compute the centroid of a GtvTetrahedron as the mean of the four vertex positions.
Parameters
t a GtvTetrahedron;
c a ::GtsPoint, whose components will be set to the centroid of t on successful exit.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_tetrahedron_vertices(), and GTV_WRONG_TYPE.
gdouble gtv_tetrahedron_circumradius (GtvTetrahedron * t)
Calculate the radius of the circumsphere of a GtvTetrahedron using the method given by Eric Weisstein's Mathworld.
Parameters
t a GtvTetrahedron.
Returns
the circumradius of t.
References gtv_tetrahedron_vertices(), and gtv_tetrahedron_volume().
Referenced by gtv_tetrahedron_quality_radius_ratio().
GtvTetrahedronClass* gtv_tetrahedron_class (void)
The basic class for tetrahedra in GTV.
Returns
the GtvTetrahedronClass
Referenced by gtv_cell_class(), gtv_tetrahedron_equilateral(), gtv_tetrahedron_large(), and gtv_tetrahedron_new().
GtvTetrahedron* gtv_tetrahedron_equilateral (GtvTetrahedronClass * klass, GtvFacetClass * facet_class, GtsEdgeClass * edge_class, GtsVertexClass * vertex_class, gdouble len)
Generate an equilateral tetrahedron.
Parameters
klass a GtvTetrahedronClass;
facet_class a GtvFacetClass;
edge_class a ::GtsEdgeClass;
vertex_class a ::GtsVertexClass;
len the length of a side of the tetrahedron.
Returns
a GtvTetrahedron with vertices at (len,0,0), (- len, len/2,0) and (0,0, len).
References gtv_facet_new(), gtv_tetrahedron_class(), and gtv_tetrahedron_new().
GtvFacet* gtv_tetrahedron_facet_opposite (GtvTetrahedron * t, GtsVertex * v)
Find the face of a tetrahedron which is opposite a specified vertex.
Parameters
t GtvTetrahedron;
v ::GtsVertex opposite to which a GtvFacet is to be found.
Returns
GtvFacet of t which is opposite v, if v is on t, NULL otherwise.
References gtv_tetrahedron_vertices().
Referenced by gtv_delaunay_add_vertex_to_cell().
gint gtv_tetrahedron_facets (GtvTetrahedron * t, GtvFacet ** f1, GtvFacet ** f2, GtvFacet ** f3, GtvFacet ** f4)
Find the facets of a tetrahedron.
Parameters
t GtvTetrahedron;
f1 GtvFacet of first face;
f2 GtvFacet of second face;
f3 GtvFacet of third face;
f4 GtvFacet of fourth face.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, and GTV_WRONG_TYPE.
GtvTetrahedron* gtv_tetrahedron_from_facets (GtvFacet * f1, GtvFacet * f2, GtvFacet * f3, GtvFacet * f4)
Find a tetrahedron which uses a set of facets.
Parameters
f1 a GtvFacet;
f2 a GtvFacet;
f3 a GtvFacet;
f4 a GtvFacet.
Returns
a GtvTetrahedron which uses f1, f2, f3 and f4, if one exists, NULL otherwise.
References gtv_tetrahedron_has_facet().
Referenced by gtv_cell_new_from_vertices(), gtv_tetrahedron_from_vertices(), and gtv_tetrahedron_new_from_vertices().
GtvTetrahedron* gtv_tetrahedron_from_vertices (GtsVertex * v1, GtsVertex * v2, GtsVertex * v3, GtsVertex * v4)
Make a new GtvTetrahedron from existing connections between four vertices.
Parameters
v1 a GtsVertex;
v2 a GtsVertex;
v3 a GtsVertex;
v4 a GtsVertex.
Returns
a GtvTetrahedron which uses facets connecting v1, v2, v3 and v4, and NULL if any of these facets do not exist.
References gtv_tetrahedron_from_facets().
gboolean gtv_tetrahedron_has_edge (GtvTetrahedron * t, GtsEdge * e)
Check if a GtvTetrahedron has a given GtsEdge.
Parameters
t a GtvTetrahedron;
e a GtsEdge.
Returns
TRUE if a facet of t uses e, FALSE otherwise.
gboolean gtv_tetrahedron_has_facet (GtvTetrahedron * t, GtvFacet * f)
Check if a tetrahedron has a given facet.
Parameters
t a GtvTetrahedron;
f a GtvFacet.
Returns
TRUE if t contains f, FALSE otherwise.
Referenced by gtv_tetrahedron_from_facets(), and gtv_tetrahedron_vertex_opposite().
gboolean gtv_tetrahedron_has_vertex (GtvTetrahedron * t, GtsVertex * v)
Check if a GtvTetrahedron has a given GtsVertex.
Parameters
t a GtvTetrahedron;
v a GtsVertex.
Returns
TRUE v is a vertex of t, FALSE otherwise.
References GTV_NULL_ARGUMENT, gtv_tetrahedron_vertices(), and GTV_WRONG_TYPE.
gdouble gtv_tetrahedron_inradius (GtvTetrahedron * t)
Compute the radius of the insphere of a GtvTetrahedron, using the formula given in Proposal of Benchmarks for 3D Unstructured Tetrahedral Mesh Optimization, Julien Dompierre, Paul Labbe, Francois Guibault, Ricardo Camarero, 1998.
Parameters
t a GtvTetrahedron.
Returns
the inradius of t.
References gtv_tetrahedron_volume().
Referenced by gtv_tetrahedron_quality_radius_ratio().
gint gtv_tetrahedron_invert (GtvTetrahedron * t)
Invert a tetrahedron by changing the order of two faces. This will change the sign of the tetrahedron volume.
Parameters
t GtvTetrahedron to invert.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, and GTV_WRONG_TYPE.
GtvTetrahedron* gtv_tetrahedron_is_duplicate (GtvTetrahedron * t)
Check if a tetrahedron is duplicated.
Parameters
t a GtvTetrahedron;
Returns
NULL if t is unique, otherwise the GtvTetrahedron which duplicates t.
Referenced by gtv_tetrahedron_is_okay().
GtsVertex* gtv_tetrahedron_is_encroached (GtvTetrahedron * t)
Check if any facet of a GtvTetrahedron is encroached.
Parameters
t a GtvTetrahedron.
Returns
a GtsVertex encroaching a facet of t, NULL if all facets of t are regular.
References gtv_facet_is_regular(), gtv_tetrahedron_opposite(), and gtv_tetrahedron_vertex_opposite().
gboolean gtv_tetrahedron_is_okay (GtvTetrahedron * t)
Check that a GtvTetrahedron has positive volume and is not a duplicate.
Parameters
t GtvTetrahedron to check.
Returns
TRUE if t is okay, FALSE otherwise.
References gtv_tetrahedron_is_duplicate(), and gtv_tetrahedron_volume().
GtvTetrahedron* gtv_tetrahedron_large (GtvTetrahedronClass * klass, GtvFacetClass * facet_class, GtsEdgeClass * edge_class, GtsVertexClass * vertex_class, gdouble len)
Generate a `large' tetrahedron which can be used to enclose a Delaunay tetrahedralization under construction.
Parameters
klass a GtvTetrahedronClass;
facet_class a GtvFacetClass;
edge_class a ::GtsEdgeClass;
vertex_class a ::GtsVertexClass;
len a length.
Returns
a GtvTetrahedron with vertices at (0,0,len), (0,len, -len), (len, -len, -len) and (-len, -len, -len).
References gtv_facet_new(), gtv_tetrahedron_class(), and gtv_tetrahedron_new().
GtvTetrahedron* gtv_tetrahedron_new (GtvTetrahedronClass * klass, GtvFacet * f1, GtvFacet * f2, GtvFacet * f3, GtvFacet * f4)
Generate a new tetrahedron from four GtvFacet's
Parameters
klass a GtvTetrahedronClass
f1 GtvFacet
f2 GtvFacet
f3 GtvFacet
f4 GtvFacet
Returns
the new GtvTetrahedron
References gtv_tetrahedron_class(), and gtv_tetrahedron_set().
Referenced by gtv_tetrahedron_equilateral(), gtv_tetrahedron_large(), and gtv_tetrahedron_new_from_vertices().
GtvTetrahedron* gtv_tetrahedron_new_from_vertices (GtvTetrahedronClass * klass, GtvFacetClass * facet_class, GtsEdgeClass * edge_class, GtsVertex * v1, GtsVertex * v2, GtsVertex * v3, GtsVertex * v4)
Generate a new tetrahedron from four ::GtsVertex's, making use of any existing GtvFacet's which connect them.
Parameters
klass a GtvTetrahedronClass
facet_class a GtvFacetClass
edge_class a ::GtsEdgeClass
v1 a ::GtsVertex
v2 a ::GtsVertex
v3 a ::GtsVertex
v4 a ::GtsVertex
Returns
the new GtvTetrahedron
References gtv_tetrahedron_from_facets(), and gtv_tetrahedron_new().
GtvTetrahedron* gtv_tetrahedron_opposite (GtvTetrahedron * t, GtvFacet * f)
Find the tetrahedron neighbouring a specified tetrahedron on a given side.
Parameters
t a GtvTetrahedron
f a GtvFacet of t
Returns
the GtvTetrahedron which neighbours t on the side f, if there is one, otherwise NULL.
Referenced by gtv_delaunay_add_vertex_to_cell(), gtv_point_locate(), gtv_tetrahedra_wedge_neighbour(), and gtv_tetrahedron_is_encroached().
gint gtv_tetrahedron_opposite_vertices (GtvTetrahedron * t, GtsVertex * v, GtsVertex ** v1, GtsVertex ** v2, GtsVertex ** v3)
Find the three vertices of a GtvTetrahedron opposite a given ::GtsVertex of the tetrahedron, respecting the orientation of the tetrahedron. On exit, v1, v2 and v3 will be the vertices of the facet of t opposite v, such that the orientation of v, v1, v2 and v3 will be the same as that of the tetrahedron itself, including the sign.
Parameters
t a GtvTetrahedron;
v a ::GtsVertex;
v1 a ::GtsVertex;
v2 a ::GtsVertex;
v3 a ::GtsVertex.
Returns
GTV_SUCCESS or GTV_FAILURE if v is not a vertex of t.
References GTV_FAILURE, GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_tetrahedron_vertices(), and GTV_WRONG_TYPE.
gint gtv_tetrahedron_orient (GtvTetrahedron * t)
Orient the facets of a tetrahedron so that it has non-negative volume.
Parameters
t a GtvTetrahedron;
Returns
GTV_SUCCESS on success, i.e. t has positive volume.
References GTV_FAILURE, GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_tetrahedron_volume(), and GTV_WRONG_TYPE.
gdouble gtv_tetrahedron_orientation (GtvTetrahedron * t)
Find the orientation of the vertices of a tetrahedron. This is an approximation of six times the signed volume of the tetrahedron.
Parameters
t a GtvTetrahedron.
Returns
a positive value if the tetrahedron apex lies above the plane of the other three points, taken in cyclic order; a negative value if it lies below that plane and zero if it lies in the plane.
References gtv_tetrahedron_vertices().
gdouble gtv_tetrahedron_quality_radius_ratio (GtvTetrahedron * t)
Calculate the radius ratio quality measure for a GtvTetrahedron, as in Proposal of Benchmarks for 3D Unstructured Tetrahedral Mesh Optimization, Julien Dompierre, Paul Labbe, Francois Guibault, Ricardo Camarero, 1998. This is three times the ratio of the inradius and the circumradius of t and will be one for an equilateral tetrahedron.
Parameters
t a GtvTetrahedron.
Returns
the radius ratio quality measure of t.
References gtv_tetrahedron_circumradius(), and gtv_tetrahedron_inradius().
gdouble gtv_tetrahedron_radius_ratio (GtvTetrahedron * t)
Calculate the radius ratio quality measure for a GtvTetrahedron, given in Dompierre, Julien, Labbe', Paul, Guibault, Francois and Camarero, Ricardo, `Proposal of benchmarks for 3D unstructured tetrahedral mesh optimization',
The measure is three times the ratio of the inradius and circumradius of the tetrahedron (although computed in a different way).
Parameters
t a GtvTetrahedron.
Returns
the radius ratio quality measure or zero if t is degenerate.
References gtv_tetrahedron_volume().
gint gtv_tetrahedron_set (GtvTetrahedron * tetrahedron, GtvFacet * f1, GtvFacet * f2, GtvFacet * f3, GtvFacet * f4)
Set the facets of a GtvTetrahedron. A check is performed to ensure that the facets define a valid tetrahedron.
Parameters
tetrahedron a GtvTetrahedron;
f1 a GtvFacet;
f2 a GtvFacet;
f3 a GtvFacet;
f4 a GtvFacet.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_REPEATED_ARGUMENT, GTV_SUCCESS, and GTV_WRONG_TYPE.
Referenced by gtv_cell_new(), and gtv_tetrahedron_new().
GtsVertex* gtv_tetrahedron_vertex_opposite (GtvTetrahedron * t, GtvFacet * f)
Find the vertex of a tetrahedron which is opposite a specified face.
Parameters
t GtvTetrahedron;
f GtvFacet opposite to which a ::GtsVertex is to be found.
Returns
::GtsVertex of t which is opposite f, if f is on t, NULL otherwise.
References gtv_tetrahedron_has_facet().
Referenced by gtv_delaunay_add_vertex_to_cell(), gtv_facet_is_regular(), gtv_facet_tetrahedra_vertices(), and gtv_tetrahedron_is_encroached().
gint gtv_tetrahedron_vertices (GtvTetrahedron * t, GtsVertex ** v1, GtsVertex ** v2, GtsVertex ** v3, GtsVertex ** v4)
Extract the vertices of a tetrahedron. These are ordered so that v1 is opposite the first face of t (t->f1) and so on.
Parameters
t a GtvTetrahedron;
v1 a ::GtsVertex;
v2 a ::GtsVertex;
v3 a ::GtsVertex;
v4 a ::GtsVertex.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, and GTV_WRONG_TYPE.
Referenced by gtv_bbox_tetrahedra(), gtv_delaunay_add_vertex_to_cell(), gtv_point_in_tetrahedron(), gtv_point_in_tetrahedron_facet(), gtv_point_in_tetrahedron_sphere(), gtv_tetrahedron_centroid(), gtv_tetrahedron_circumradius(), gtv_tetrahedron_facet_opposite(), gtv_tetrahedron_has_vertex(), gtv_tetrahedron_opposite_vertices(), gtv_tetrahedron_orientation(), gtv_tetrahedron_vertices_off_edge(), and gtv_tetrahedron_volume().
gint gtv_tetrahedron_vertices_off_edge (GtvTetrahedron * t, GtsEdge * e, GtsVertex ** a, GtsVertex ** b)
Find the vertices of a GtvTetrahedron which are not used by a GtsEdge. If e is not used by t, a and b will be NULL.
Parameters
t a GtvTetrahedron;
e a GtsEdge;
a on exit, a GtsVertex of t which does not lie on e
b on exit, the other GtsVertex of t which does not lie on e.
Returns
GTV_SUCCESS on success.
References GTV_FAILURE, GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_tetrahedron_vertices(), and GTV_WRONG_TYPE.
gdouble gtv_tetrahedron_volume (GtvTetrahedron * t)
Find the signed volume of a tetrahedron.
Parameters
t a GtvTetrahedron.
Returns
the signed volume of t; if this is negative, you might want to use gtv_tetrahedron_invert or gtv_tetrahedron_orient to reorient the vertices.
References gtv_tetrahedron_vertices().
Referenced by gtv_tetrahedron_circumradius(), gtv_tetrahedron_inradius(), gtv_tetrahedron_is_okay(), gtv_tetrahedron_orient(), and gtv_tetrahedron_radius_ratio().