GTV: Facets
Facets
Data Structures
struct GtvFacet
struct GtvFacetClass
Functions
GtvFacet * gtv_facet_new (GtvFacetClass *klass, GtsEdge *e1, GtsEdge *e2, GtsEdge *e3)
GtvCell * gtv_facet_is_boundary (GtvFacet *f, GtvVolume *v)
gint gtv_facet_tetrahedra_vertices (GtvFacet *f, GtsVertex **v1, GtsVertex **v2, GtsVertex **v3, GtsVertex **v4, GtsVertex **v5)
gint gtv_facet_tetrahedra (GtvFacet *f, GtvTetrahedron **t1, GtvTetrahedron **t2)
GtvFacet * gtv_facet_from_vertices (GtsVertex *v1, GtsVertex *v2, GtsVertex *v3)
gboolean gtv_facet_has_vertex (GtvFacet *f, GtsVertex *v)
gboolean gtv_facet_has_edge (GtvFacet *f, GtsEdge *e)
GtvCell * gtv_edge_is_boundary (GtsEdge *e, GtvVolume *v)
GtvCell * gtv_vertex_is_boundary (GtsVertex *p, GtvVolume *v)
Detailed Description
Function Documentation
GtvCell* gtv_edge_is_boundary (GtsEdge * e, GtvVolume * v)
Check if a GtsEdge lies on the boundary of a GtvVolume.
Parameters
e a ::GtsEdge;
v a GtvVolume or NULL.
Returns
a GtvCell which uses e and is on the boundary of v.
References gtv_facet_is_boundary().
Referenced by gtv_delaunay_add_vertex_to_cell(), and gtv_vertex_is_boundary().
GtvFacet* gtv_facet_from_vertices (GtsVertex * v1, GtsVertex * v2, GtsVertex * v3)
Find a GtvFacet which uses three given ::GtsVertex's.
Parameters
v1 a ::GtsVertex;
v2 a ::GtsVertex;
v3 a ::GtsVertex.
Returns
a GtvFacet which uses v1, v2 and v3, if it exists, NULL otherwise.
gboolean gtv_facet_has_edge (GtvFacet * f, GtsEdge * e)
Check if a GtvFacet uses a ::GtsEdge.
Parameters
f a GtvFacet;
e a ::GtsEdge;
Returns
TRUE if f use e, FALSE otherwise.
gboolean gtv_facet_has_vertex (GtvFacet * f, GtsVertex * v)
Check if a GtvFacet uses a ::GtsVertex.
Parameters
f a GtvFacet;
v a ::GtsVertex;
Returns
TRUE if f use v, FALSE otherwise.
GtvCell* gtv_facet_is_boundary (GtvFacet * f, GtvVolume * v)
Check if a GtvFacet lies on the boundary of a GtvVolume.
Parameters
f a GtvFacet;
v a GtvVolume or NULL.
Returns
a GtvCell which uses f and is on the boundary of v.
References gtv_cell_has_parent_volume().
Referenced by gtv_delaunay_add_vertex_to_cell(), and gtv_edge_is_boundary().
GtvFacet* gtv_facet_new (GtvFacetClass * klass, GtsEdge * e1, GtsEdge * e2, GtsEdge * e3)
Make a new GtvFacet from three edges which must define a proper triangle.
Parameters
klass a GtvFacetClass;
e1 a ::GtsEdge;
e2 a ::GtsEdge;
e3 a ::GtsEdge.
Returns
a new GtvFacet or NULL if the edges do not define a valid triangle.
Referenced by gtv_tetrahedron_equilateral(), gtv_tetrahedron_large(), and gtv_volume_read().
gint gtv_facet_tetrahedra (GtvFacet * f, GtvTetrahedron ** t1, GtvTetrahedron ** t2)
Find the tetrahedra which use a GtvFacet.
Parameters
f a GtvFacet
t1 a GtvTetrahedron which uses f or NULL if f is isolated;
t2 a GtvTetrahedron which uses f or NULL if f is a boundary facet.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, and GTV_WRONG_TYPE.
gint gtv_facet_tetrahedra_vertices (GtvFacet * f, GtsVertex ** v1, GtsVertex ** v2, GtsVertex ** v3, GtsVertex ** v4, GtsVertex ** v5)
Find the vertices of the tetrahedra sharing a particular facet. If f is used by only one tetrahedron, v5 will be NULL. If f is an isolated facet, i.e. not used by any tetrahedra, all the vertices will be NULL.
Parameters
f a GtvFacet
v1 a vertex of a tetrahedron using f;
v2 a vertex of a tetrahedron using f;
v3 a vertex of a tetrahedron using f;
v4 a vertex of a tetrahedron using f;
v5 a vertex of a tetrahedron using f.
Returns
GTV_SUCCESS on success.
References GTV_NULL_ARGUMENT, GTV_SUCCESS, gtv_tetrahedron_vertex_opposite(), and GTV_WRONG_TYPE.
GtvCell* gtv_vertex_is_boundary (GtsVertex * p, GtvVolume * v)
Check if a GtsVertex lies on the boundary of a GtvVolume.
Parameters
p a ::GtsVertex;
v a GtvVolume or NULL.
Returns
a GtvCell which uses p and is on the boundary of v.
References gtv_edge_is_boundary().